---
driver_plugin: <%= ENV['AWS_ACCESS_KEY_ID'] ? "ec2" : "vagrant" %>

platforms:
<% if ENV['AWS_ACCESS_KEY_ID'] %>
- name: precise64_ec2
  driver_plugin: ec2
  driver_config:
    aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    # Default keypair is in Stark & Wayne AWS account for kitchen CI testing
    aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_NAME'] || 'kitchen' %> # name of the AWS keypair to use
    ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] || File.expand_path("../config/ssh/kitchen-aws", __FILE__) %> # private key such as ~/.ssh/id_rsa that matches the AWS keypair
    region: us-east-1
    availability_zone: us-east-1b
    flavor_id: m1.medium
    image_id: ami-856f02ec # us-east-1 12.04 amd64
    username: ubuntu
    groups:
      - default
      - ssh
    require_chef_omnibus: true
<% else %>
- name: precise64_virtualbox
  driver_config:
    provider: virtualbox
    box: precise64
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: true
- name: precise64_vmware_fusion
  driver_config:
    provider: vmware_fusion
    box: precise64
    box_url: https://s3.amazonaws.com/gsc-vagrant-boxes/ubuntu-12.04.2-server-amd64.box
    require_chef_omnibus: true
<% end %>

suites:
- name: default
  run_list:
    - recipe[bosh_inception]
  attributes: {}
