include_recipe "bosh_inception::vcap_user"
include_recipe "bosh_inception::useful_dirs"
include_recipe "bosh_inception::packages"
include_recipe "bosh_inception::git_config"
include_recipe "bosh_inception::ruby"
